### ISSUE TITLE
Show publication date at beginnig of blog entry

### ISSUE THREAD

**Issue by GeckoEidechse** [Alystrasz/NorthstarBlog#7]
In general it is common for (news) articles to display their publication date at the beginning so that it's clear to the reader whether that content might actually still be relevant or not.

We do have a thing at the end for last updated

![image](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/2a543a0b-37c5-4ff4-9e48-5506ae63f5bd)

But something that says _"published on"_ would be nice. Would put it somewhere like here:

![image](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/5dbf88e3-7c3e-4a53-a90d-6cf0074f9feb)

**Comment by Alystrasz** [comment]
Addressed with 05a4966a83c2a7eafd90b4c22c3e12953ded5880.

**Comment by GeckoEidechse** [comment]
Confirmed :D

![image](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/67498067-dbee-419c-a8b2-31bc4bc59e92)
