### ISSUE TITLE
Fix one-year-anniversary post creation time

### ISSUE THREAD

**Issue by GeckoEidechse** [Alystrasz/NorthstarBlog#8]
Going over https://northstar.tf/blog/one-year/ I noticed the creation date says `December 21, 2022`

![image](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/a1ad7f51-0c94-4c4f-96c5-d0d9bf9e5de3)

However, the post mentions that Northstar was released over 365 days ago which doesn't match up (release date was 2021-12-24).

Given that we set the "official" anniversary to January 8th, we might wanna update the post to have the same creation date ^^

**Comment by Alystrasz** [comment]
Fixed with 93cf2c39713b1bc341b73ab00f01b3003e8dd6b4.
