### ISSUE TITLE
Cannot clone/checkout on Windows

### ISSUE THREAD

**Issue by GeckoEidechse** [Alystrasz/NorthstarBlog#9]
![image](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/3c719e83-cb44-4b4d-b9a2-2ba63b204af6)

`:` is not allowed in filenames on Windows

- https://github.com/Alystrasz/NorthstarBlog/blob/4654b741440c598d908fccfc6bf6e0702432c24b/assets/images/favicon.ico%3AZone.Identifier
- https://github.com/Alystrasz/NorthstarBlog/blob/4654b741440c598d908fccfc6bf6e0702432c24b/assets/images/favicon-128.png%3AZone.Identifier

**Comment by Alystrasz** [comment]
Are those `:Zone.Identifier` files useful?
They seem empty, so we could just delete them.

**Comment by Alystrasz** [comment]
Fixed with 78bd1c8db7eb4d8e054eb5563c355ac438b80bfc, 9fb53e986b838e1cbd9b46d4e9bc94141818018e and 6f3a3359e754935b5d764b40cb0d4c1c26c03ddd.
